# Generated by Django 4.2.3 on 2023-07-21 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='slug',
            field=models.SlugField(default=None, max_length=200, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='status',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Статус профиля'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
    ]
