# Generated by Django 4.2.3 on 2023-07-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0002_advuser_slug_alter_advuser_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Слаг'),
        ),
    ]
