# Generated by Django 4.2.3 on 2023-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0005_post_postviewcount_postlike_postfavourite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdislike',
            options={'verbose_name': 'Дизлайк комментария', 'verbose_name_plural': 'Дизлайки комментариев'},
        ),
        migrations.AlterModelOptions(
            name='commentlike',
            options={'verbose_name': 'Лайк комментария', 'verbose_name_plural': 'Лайки комментариев'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Слаг'),
        ),
    ]
