# Generated by Django 4.2.3 on 2023-08-21 14:26

from django.db import migrations, models
import gnome_main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0006_alter_commentdislike_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadditionalimage',
            name='media',
            field=models.FileField(upload_to=gnome_main.utilities.get_image_path_post_ai, verbose_name='Медиа'),
        ),
    ]
