# Generated by Django 4.2.3 on 2023-08-16 10:00

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0006_alter_commentdislike_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='avatar cropping'),
        ),
        migrations.AddField(
            model_name='advuser',
            name='profile_image_cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '1920x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='profile image cropping'),
        ),
    ]
