# Generated by Django 4.2.3 on 2023-08-16 11:17

from django.db import migrations
import gnome_main.models
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0007_advuser_avatar_cropping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=image_cropping.fields.ImageCropField(db_index=True, null=True, upload_to=gnome_main.models.AdvUser.get_profile_image_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='avatar_cropping',
            field=image_cropping.fields.ImageRatioField('avatar', '200x200', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='avatar cropping'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='profile_image',
            field=image_cropping.fields.ImageCropField(db_index=True, null=True, upload_to=gnome_main.models.AdvUser.get_profile_image_path, verbose_name='Шапка профиля'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='profile_image_cropping',
            field=image_cropping.fields.ImageRatioField('profile_image', '1920x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='profile image cropping'),
        ),
    ]
