# Generated by Django 4.2.3 on 2023-08-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0007_alter_postadditionalimage_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.TextField(max_length=500, verbose_name='Текст комментария'),
        ),
    ]
