# Generated by Django 4.2.3 on 2023-08-16 13:21

from django.db import migrations, models
import gnome_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0008_alter_advuser_avatar_alter_advuser_avatar_cropping_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='avatar_cropping',
        ),
        migrations.RemoveField(
            model_name='advuser',
            name='profile_image_cropping',
        ),
        migrations.AlterField(
            model_name='advuser',
            name='avatar',
            field=models.ImageField(db_index=True, null=True, upload_to=gnome_main.models.AdvUser.get_profile_image_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='profile_image',
            field=models.ImageField(db_index=True, null=True, upload_to=gnome_main.models.AdvUser.get_profile_image_path, verbose_name='Шапка профиля'),
        ),
    ]
