# Generated by Django 4.2.3 on 2023-08-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0008_alter_postcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Текст комментария'),
        ),
    ]
