# Generated by Django 4.2.3 on 2023-08-26 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0009_alter_postcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Текст комментария'),
        ),
    ]
