# Generated by Django 4.2.3 on 2023-08-29 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0011_alter_postcomment_comment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commentdislike',
            unique_together={('comment', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='commentlike',
            unique_together={('comment', 'user')},
        ),
    ]
