# Generated by Django 4.2.3 on 2023-08-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0012_alter_commentdislike_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postdislike',
            unique_together={('post', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
    ]
