# Generated by Django 4.2.3 on 2023-09-03 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0014_alter_postfavourite_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Дискриминация', 'Дискриминация'), ('Контент сексуального характера', 'Контент сексуального характера'), ('Нежелательный контент', 'Нежелательный контент'), ('Пропаганда наркотиков, алкоголя, табачной продукции', 'Пропаганда наркотиков, алкоголя, табачной продукции'), ('Демонстрация насилия', 'Демонстрация насилия')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnome_main.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба на запись',
                'verbose_name_plural': 'Жалобы на записи',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Дискриминация', 'Дискриминация'), ('Контент сексуального характера', 'Контент сексуального характера'), ('Нежелательный контент', 'Нежелательный контент'), ('Пропаганда наркотиков, алкоголя, табачной продукции', 'Пропаганда наркотиков, алкоголя, табачной продукции'), ('Демонстрация насилия', 'Демонстрация насилия'), ('Оскорбления', 'Оскорбления')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnome_main.postcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба на комментарий',
                'verbose_name_plural': 'Жалобы на комментарии',
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
