# Generated by Django 4.2.3 on 2023-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0016_commentreport_text_postreport_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcomment',
            name='is_changed',
            field=models.BooleanField(default=False, null=True, verbose_name='Изменён ли'),
        ),
    ]
