# Generated by Django 4.2.3 on 2023-09-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0019_posttag_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='gnome_main.posttag', verbose_name='Тэг'),
        ),
    ]
