# Generated by Django 4.2.3 on 2023-10-02 04:44

import django.core.validators
from django.db import migrations, models
import gnome_main.models


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0022_alter_post_content_alter_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(100, 'Содержание должно быть длинной минимум в 100 символов'), gnome_main.models.WordCountValidator(10)], verbose_name='Содержание'),
        ),
    ]
