# Generated by Django 4.2.3 on 2023-10-15 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gnome_main.models
import gnome_main.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0024_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AlterField(
            model_name='postadditionalimage',
            name='media',
            field=models.FileField(upload_to=gnome_main.utilities.get_image_path_post_ai, validators=[gnome_main.models.MaxFileSizeValidator(100)], verbose_name='Медиа'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnome_main.post', verbose_name='Запись'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='type',
            field=models.CharField(choices=[('Дискриминация', 'Дискриминация'), ('Контент сексуального характера', 'Контент сексуального характера'), ('Нежелательный контент', 'Нежелательный контент'), ('Пропаганда наркотиков, алкоголя, табачной продукции', 'Пропаганда наркотиков, алкоголя, табачной продукции'), ('Демонстрация насилия', 'Демонстрация насилия')], verbose_name='Тип жалобы'),
        ),
        migrations.AlterField(
            model_name='postreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
