# Generated by Django 4.2.3 on 2023-10-15 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gnome_main', '0025_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreport',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gnome_main.postcomment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='type',
            field=models.CharField(choices=[('Дискриминация', 'Дискриминация'), ('Контент сексуального характера', 'Контент сексуального характера'), ('Нежелательный контент', 'Нежелательный контент'), ('Пропаганда наркотиков, алкоголя, табачной продукции', 'Пропаганда наркотиков, алкоголя, табачной продукции'), ('Демонстрация насилия', 'Демонстрация насилия'), ('Оскорбления', 'Оскорбления')], verbose_name='Тип жалобы'),
        ),
        migrations.AlterField(
            model_name='commentreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
