from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from gnome_main.rest_api_views import *

urlpatterns = [
    # Account Controller
    path('api/account/signin/', TokenObtainPairView.as_view(), name='account-signin'),
    path('api/account/refresh/', TokenRefreshView.as_view(), name='account-refresh'),
    path('api/account/verify/', TokenVerifyView.as_view(), name='account-verify'),
    path('api/account/signup/', UserCreateAPIView.as_view(), name='account-register'),
    path('api/account/logout/', UserLogoutAPIView.as_view(), name='account-logout'),
    path('api/account/', UserChangeInfoAPIView.as_view(), name='account-info'),
    # Rubric Controller
    path('api/rubrics/<int:pk>/', RubricAPIView.as_view(), name='rubrics'),
    path('api/rubrics/', RubricListAPIView.as_view(), name='rubrics'),
    # Post Controller
    path('api/posts/filter/', PostFilterAPIView.as_view(), name='posts-filter'),
    path('api/posts/search/', PostSearchAPIView.as_view(), name='posts-search'),
    path('api/posts/favourite/', PostFavouriteAPIView.as_view(), name='posts-favourite'),
    path('api/posts/liked/', PostLikedAPIView.as_view(), name='posts-liked'),
    path('api/posts/history/', PostHistoryAPIView.as_view(), name='posts-history'),
    path('api/posts/<int:pk>/', PostRUDAPIView.as_view(), name='post-get-ud'),
    path('api/posts/', PostListCreateAPIView.as_view(), name='post-all'),
    # PostViewCount Controller
    path('api/postview/<int:pk>/', PostViewDeleteAPIView.as_view(), name='post-view-delete'),
    path('api/postview/', PostViewAPIView.as_view(), name='post-view'),
    # PostLike Controller
    path('api/postlike/<int:pk>/', PostLikeDelete.as_view(), name='post-like-delete'),
    path('api/postlike/', PostLikeCreate.as_view(), name='post-like'),
    # PostDisLike Controller
    path('api/postdislike/<int:pk>/', PostDisLikeDelete.as_view(), name='post-dislike-delete'),
    path('api/postdislike/', PostDisLikeCreate.as_view(), name='post-dislike'),
    # PostFavourite Controller
    path('api/postfavourite/<int:pk>/', PostFavouriteDelete.as_view(), name='post-favourite-delete'),
    path('api/postfavourite/', PostFavouriteCreate.as_view(), name='post-favourite'),
    # PostComment Controller
    path('api/postcomment/change-delete/<int:pk>/', PostCommentUpdateDelete.as_view(), name='post-comment-update-delete'),
    path('api/postcomment/super/', PostSuperCommentAPIView.as_view(), name='post-supercomment'),
    path('api/postcomment/sub/', PostSubCommentAPIView.as_view(), name='post-subcomment'),
    # CommentLike Controller
    path('api/commentlike/<int:pk>/', CommentLikeDeleteAPIView.as_view(), name='comment-like-delete'),
    path('api/commentlike/', CommentLikeCreateAPIView.as_view(), name='comment-like-create'),
    # CommentDisLike Controller
    path('api/commentdislike/<int:pk>/', CommentDisLikeDeleteAPIView.as_view(), name='comment-dislike-delete'),
    path('api/commentdislike/', CommentDisLikeCreateAPIView.as_view(), name='comment-dislike-create'),
    # PostReport Controller
    path('api/postreport/', PostReportAPIView.as_view(), name='post-report'),
    # CommentReport Controller
    path('api/commentreport/', CommentReportAPIView.as_view(), name='comment-report'),
    # Notification Controller
    path('api/notification/', NotificationAPIView.as_view(), name='notification'),
    # AdminUser Controller
    path('api/admin/user/<int:pk>/', AdminUserRUDAPIView.as_view(), name='admin-user'),
    path('api/admin/user/', AdminAllUsersAPIView.as_view(), name='admin-user-list-create'),
    # AdminRubric Controller
    path('api/admin/rubric/<int:pk>/', AdminRubricRUDAPIView.as_view(), name='admin-rubric'),
    path('api/admin/rubric/', AdminRubricListAPIView.as_view(), name='admin-rubric-list-create'),
    # AdminPost Controller
    path('api/admin/post/<int:pk>/', AdminPostRUDAPIView.as_view(), name='admin-post'),
    path('api/admin/post/', AdminPostListCreateAPIView.as_view(), name='admin-post-list-create'),
    # AdminPostViewCount Controller
    path('api/admin/postview/<int:pk>/', AdminPostViewDeleteAPIView.as_view(), name='admin-post-view-delete'),
    path('api/admin/postview/', AdminPostViewAPIView.as_view(), name='admin-post-view'),
    # AdminPostLike Controller
    path('api/admin/postlike/<int:pk>/', AdminPostLikeDelete.as_view(), name='admin-post-like-delete'),
    path('api/admin/postlike/', AdminPostLikeCreate.as_view(), name='admin-post-like'),
    # AminPostDisLike Controller
    path('api/admin/postdislike/<int:pk>/', AdminPostDisLikeDelete.as_view(), name='admin-post-dislike-delete'),
    path('api/admin/postdislike/', AdminPostDisLikeCreate.as_view(), name='admin-post-dislike'),
    # AdminPostFavourite Controller
    path('api/admin/postfavourite/<int:pk>/', AdminPostFavouriteDelete.as_view(), name='admin-post-favourite-delete'),
    path('api/admin/postfavourite/', AdminPostFavouriteCreate.as_view(), name='admin-post-favourite'),
    # AdminPostComment Controller
    path('api/admin/postcomment/<int:pk>/', AdminPostCommentUpdateAPIView.as_view(), name='admin-post-comment-update-delete'),
    path('api/admin/postcomment/', AdminPostCommentListCreateAPIView.as_view(), name='admin-post-comment'),
    # AdminCommentLike Controller
    path('api/admin/commentlike/<int:pk>/', AdminCommentLikeDeleteAPIView.as_view(), name='admin-comment-like-delete'),
    path('api/admin/commentlike/', AdminCommentLikeCreateAPIView.as_view(), name='admin-comment-like-create'),
    # AdminCommentDisLike Controller
    path('api/admin/commentdislike/<int:pk>/', AdminCommentDisLikeDeleteAPIView.as_view(), name='admin-comment-dislike-delete'),
    path('api/admin/commentdislike/', AdminCommentDisLikeCreateAPIView.as_view(), name='admin-comment-dislike-create'),
    # AdminPostReport Controller
    path('api/admin/postreport/<int:pk>/', AdminPostReport.as_view(), name='admin-post-report'),
    path('api/admin/postreport/', AdminPostReportList.as_view(), name='admin-post-report-list'),
    # AdminCommentReport Controller
    path('api/admin/commentreport/<int:pk>/', AdminCommentReport.as_view(), name='admin-comment-report'),
    path('api/admin/commentreport/', AdminCommentReportList.as_view(), name='admin-comment-report-list'),
    # AdminNotification Controller
    path('api/admin/notification/<int:pk>/', AdminNotificationRUDAPIView.as_view(), name='admin-notification'),
    path('api/admin/notification/', AdminNotificationListCreateAPIView.as_view(), name='admin-notification-list-create'),
]